FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app/SecretMagic

# copy csproj and restore as distinct layers
COPY *.sln .
COPY SecretMagic.API/. ./SecretMagic.API/
COPY SecretMagic.Model/. ./SecretMagic.Model/
COPY SecretMagic.Repository/. ./SecretMagic.Repository/
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app/SecretMagic
COPY --from=build /app/SecretMagic/out ./
ENTRYPOINT ["dotnet", "SecretMagic.API.dll"]